### ISSUE TITLE
Thaumcraft: Electro-Magic Tools Electric boots of the Traveller recharging on re equip

### ISSUE THREAD

**Issue by Trungar** [xJon/Tekkit-SMP#12]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

Electric boots of the Traveller,  recharging on re equip  Also works with nano/quantum  How to reproduce : (Must be in Survival mode) :  1 Charge a Electric Boots of the Traveler, equip it run and or jump some distance  2 Open inventory & double left click boots to recharge them.

**Comment by xJon** [comment]
This is now fixed in version `1.0.2` :)
