### ISSUE TITLE
Thaumcraft: Electro-Magic Tools Nano/Quantum boots of the Traveller fall damage

### ISSUE THREAD

**Issue by Trungar** [xJon/Tekkit-SMP#13]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

In the Thaumcraft Electro-Magic Tools, the section for the nano boots says they negate fall damage completely. This is not the case for them or the upgraded version quantum travelers boots,   How to reproduce: fall from a high distance wearing the charged nanoboots/quantum boots.

**Comment by xJon** [comment]
This is now fixed in version `1.0.2`!
