### ISSUE TITLE
Nether Star 

### ISSUE THREAD

**Issue by Paperfox9** [xJon/Tekkit-SMP#16]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

Tekkit SMP EMC value for The nether star doesn't exist, in Tekkit 2 their is an EMC value for Nether star but for Tekkit SMP, As well doesnt work with the Transmute option doesnt work nether, Cannot as well put into Energy condenser  
![Screenshot (13)](https://github.com/user-attachments/assets/8bcaaab3-ba37-4d1c-8f1f-00a6af1269fb)

**Comment by xJon** [comment]
Hi! This is intentional. In Tekkit SMP you are encouraged to farm Nether Stars (e.g. with a Wither Builder). In Tekkit 2 they didn't really have any use, so they had an EMC value by default.
