### ISSUE TITLE
No Tooltips for Industrial Craft Items

### ISSUE THREAD

**Issue by Mandaroni** [xJon/Tekkit-SMP#17]
### Was this help requested before?

- [X] No, it was not.

### If you have any, please provide a list of additional mods

Industrial Craft

### Please describe what you need help with

The inventory does not show me more detailed tooltips for IndustrialCraft items. For example, how much EU the generator outputs or what an MFE can output, etc. Funnily enough, it worked once and then suddenly didn't work again. Help would be appreciated.

**Comment by xJon** [comment]
You need an [EU Reader](https://github.com/TinyModularThings/IC2Classic/wiki/EU-Reader)!

**Comment by Mandaroni** [comment]
Thanks for the quick response. But I think I did not express myself correctly. I don't mean when they are placed and in use. Then I know I can use the EU Reader so see the current on wires. But I mean when I hover over an Item in my Inventory or in JEI. I see the Name of the item but no more information (like max Output from the Generator or max current a cable can handle) in the tooltip. Like I said it worked for a day and then disappeared ¯\_(ツ)_/¯

**Comment by Mandaroni** [comment]
Oh no your right. I'm stupid :D
