### ISSUE TITLE
Server Pack has newer mods then client

### ISSUE THREAD

**Issue by lupleime** [xJon/Tekkit-SMP#18]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

I just updated my Server and Client to the latest version, but after not being able to join my server anymore. i found out that the server has newer version of mods then the client. i tried fully reinstalling the client but that didnt change anything

both server and client are on 1.0.2
here is a file compare between both mods folders
![image](https://github.com/user-attachments/assets/fc164aca-5e35-408d-93b3-3210cb22ca65)

**Comment by xJon** [comment]
Hi! I'm unable to reproduce this. Can you download the server pack again?

**Comment by lupleime** [comment]
Oh that weird it just works now.🫠
