### ISSUE TITLE
Logistics Pipes IC2 Power Supplier Upgrade not working

### ISSUE THREAD

**Issue by Ramog** [xJon/Tekkit-SMP#26]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

If you setup an `EU Power Provider` and create a working [power network for your LP-System](https://ftb.fandom.com/wiki/Getting_Started_(Logistics_Pipes)#Transporting_Power) it will not work unless you leave the world and load it again.
**But even then** only the laser beam in the pipes shows up, no power is put into the machine that the `IC2 Power Supplier Upgrade` is attached to.
I was told that this is unique to EU, the RF part of this system seems to work without problem.

https://github.com/RS485/LogisticsPipes/issues/1712

**Comment by xJon** [comment]
Hey! Could you also report it in the [Logistics Pipes repo](https://github.com/RS485/LogisticsPipes/issues)?
I wonder whether as a temporary "workaround" I should hide the `IC2 Power Supplier Upgrade` from JEI to encourage players to convert to and use RF instead.

**Comment by Ramog** [comment]
> Hey! Could you also report it in the [Logistics Pipes repo](https://github.com/RS485/LogisticsPipes/issues)?

I will see what I can do
> I wonder whether as a temporary "workaround" I should hide the `IC2 Power Supplier Upgrade` from JEI to encourage players to convert to and use RF instead.

Isn't that a bit backwards tho, considering tekkit 2/smp tries to push IC2 whenever possible?

**Comment by xJon** [comment]
@Ramog Oh yes, I misunderstood. In that case it seems this feature of Logistics Pipes has no use at this point.

**Comment by xJon** [comment]
Thank you for the report - closing due to https://github.com/RS485/LogisticsPipes/issues/1712#issuecomment-2501067202.
