### ISSUE TITLE
Multiplayer: Logistic pipe's active supply module frequently resets its settings or stops working

### ISSUE THREAD

**Issue by RolilithMordebricks** [xJon/Tekkit-SMP#29]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

im not sure how to reproduce this

**Comment by xJon** [comment]
How commonly does this issue occur? I'm not sure how helpful it is to report this issue as-is to the mod author.

**Comment by xJon** [comment]
Closing because of the Discord message.
