### ISSUE TITLE
Crash on Multiplayer

### ISSUE THREAD

**Issue by ArthurHetem** [xJon/Tekkit-SMP#3]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/Nb6t9HR

### Please describe the issue you are experiencing

My friend was playing with me normally, yesterday we played like 4 hours. Today we started playing and then he crashed, when he tried to login again, he crashed again and cannot login anymore, always have the same crash

**Comment by xJon** [comment]
Thank you for the report! Will try to patch this in the next update.
In the meantime, you can try to edit their player data to remove the jetpack (I think [NBTExplorer](https://github.com/jaquadro/NBTExplorer) is still used), or rollback to a backup of their player data.

**Comment by xJon** [comment]
Adding context from Discord:
> If you charge a lappack (bauble slot jetpack) in a MFE, you get a crash, subsequent attempts to get back into the world keep on getting the same type of crash. Reproduced with just a lappack and a MFSU (add some energy to the MFSU, charge the lappack a bit and then attempt to take it out)

**Comment by xJon** [comment]
Will be fixed in the next update (coming later today) thanks to @ACGaming!
The next update will also let you enter worlds that have been crashing in `1.0.0` due to this bug.

**Comment by xJon** [comment]
Resolved in `1.0.1`.
