### ISSUE TITLE
Project E Missing Textures Bug

### ISSUE THREAD

**Issue by LynxSlayer** [xJon/Tekkit-SMP#4]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

While using the Red Matter Shovel (from Project E) Special ability, it will randomly change textures to the missing textures icon (black and pink checkered pattern).
![SMP missing](https://github.com/user-attachments/assets/9856d756-bbc6-47b3-9a2d-1ab4f00ae56a)

**Comment by xJon** [comment]
When you say special ability, what exactly are you referring to?

**Comment by LynxSlayer** [comment]
The Special ability when you press C
https://mclo.gs/kUukW3g - I believe this is the log you want, if not can you please give me the path.

**Comment by xJon** [comment]
@LynxSlayer I don't believe the Red Matter Shovel has any Extra Function abilities? I'm still unable to reproduce this.

**Comment by LynxSlayer** [comment]
Ha after investigating, it's clashing with one of the plugins that we have on the server.
![image](https://github.com/user-attachments/assets/1448b21f-8d8b-414a-8b4f-b4257bd3459a)
After turning it off in setting in-game, it no longer happening.

**Comment by LynxSlayer** [comment]
This is our side on the plugin, thank you for your time anyways.
